version: 2.1

executors:
  rust-executor:
    docker:
      - image: cimg/rust:1.92

jobs:
  check:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: Run cargo format
          command: cargo fmt -- --check
      - run:
          name: Install cargo audit
          command: cargo install cargo-audit --locked
      - run:
          name: Run cargo audit
          command: cargo audit
      - run:
          name: Install cargo machete
          command: cargo install cargo-machete --locked
      - run:
          name: Run cargo machete
          command: cargo machete
      - run:
          name: Install cargo deny
          command: cargo install cargo-deny --locked
      - run:
          name: Run cargo deny
          command: cargo deny check
  build:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: Run cargo build
          command: cargo build
      - persist_to_workspace:
          root: target
          paths:
            - debug
  clippy:
    executor: rust-executor
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run:
          name: Install clippy
          command: rustup component add clippy
      - run:
          name: Run clippy
          command: cargo clippy --all-targets --all-features -- -D warnings
  test:
    executor: rust-executor
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run:
          name: Run cargo test
          command: cargo test --all-features

workflows:
  production:
    jobs:
      - check
      - build:
          requires:
            - check
      - clippy:
          requires:
            - build
      - test:
          requires:
            - build
